version: '20.10.17'
services:
  api:
    build: .
    ports:
      - "5000:8080"
    links:
      - "postgres"
  postgres:
    image: postgres:14
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
